"""create_initial_schema

Revision ID: a463b296fdce
Revises: 
Create Date: 2026-09-27 22:03:55.188979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a463b296fdce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('asset_type', sa.Enum('VEHICLE', 'HVAC', 'APPLIANCE', 'OTHER', name='asset_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_is_deleted'), 'assets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_updated_at'), 'assets', ['updated_at'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=80), nullable=False),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_value_at_service', sa.Float(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_asset_id'), 'maintenance_logs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_is_deleted'), 'maintenance_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_maintenance_type'), 'maintenance_logs', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_service_date'), 'maintenance_logs', ['service_date'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_updated_at'), 'maintenance_logs', ['updated_at'], unique=False)
    op.create_table('maintenance_rules',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=80), nullable=False),
    sa.Column('metric_type', sa.Enum('ODOMETER', 'TIME_DAYS', 'TIME_MONTHS', 'USAGE_HOURS', name='metric_type_enum'), nullable=False),
    sa.Column('interval_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_rules_asset_id'), 'maintenance_rules', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_rules_is_deleted'), 'maintenance_rules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_maintenance_rules_maintenance_type'), 'maintenance_rules', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_maintenance_rules_updated_at'), 'maintenance_rules', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_rules_updated_at'), table_name='maintenance_rules')
    op.drop_index(op.f('ix_maintenance_rules_maintenance_type'), table_name='maintenance_rules')
    op.drop_index(op.f('ix_maintenance_rules_is_deleted'), table_name='maintenance_rules')
    op.drop_index(op.f('ix_maintenance_rules_asset_id'), table_name='maintenance_rules')
    op.drop_table('maintenance_rules')
    op.drop_index(op.f('ix_maintenance_logs_updated_at'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_service_date'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_maintenance_type'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_is_deleted'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_asset_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_assets_updated_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_is_deleted'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
